// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoParserFound.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "NoParserFound.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* NoParserFound_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NoParserFound_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_NoParserFound_2eproto() {
  protobuf_AddDesc_NoParserFound_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "NoParserFound.proto");
  GOOGLE_CHECK(file != NULL);
  NoParserFound_descriptor_ = file->message_type(0);
  static const int NoParserFound_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NoParserFound, requestedparserid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NoParserFound, receivedmessageid_),
  };
  NoParserFound_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NoParserFound_descriptor_,
      NoParserFound::default_instance_,
      NoParserFound_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NoParserFound, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NoParserFound, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NoParserFound));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_NoParserFound_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NoParserFound_descriptor_, &NoParserFound::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_NoParserFound_2eproto() {
  delete NoParserFound::default_instance_;
  delete NoParserFound_reflection_;
}

void protobuf_AddDesc_NoParserFound_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023NoParserFound.proto\"E\n\rNoParserFound\022\031"
    "\n\021requestedParserID\030\001 \002(\r\022\031\n\021receivedMes"
    "sageID\030\002 \002(\r", 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NoParserFound.proto", &protobuf_RegisterTypes);
  NoParserFound::default_instance_ = new NoParserFound();
  NoParserFound::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_NoParserFound_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_NoParserFound_2eproto {
  StaticDescriptorInitializer_NoParserFound_2eproto() {
    protobuf_AddDesc_NoParserFound_2eproto();
  }
} static_descriptor_initializer_NoParserFound_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int NoParserFound::kRequestedParserIDFieldNumber;
const int NoParserFound::kReceivedMessageIDFieldNumber;
#endif  // !_MSC_VER

NoParserFound::NoParserFound()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NoParserFound::InitAsDefaultInstance() {
}

NoParserFound::NoParserFound(const NoParserFound& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NoParserFound::SharedCtor() {
  _cached_size_ = 0;
  requestedparserid_ = 0u;
  receivedmessageid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NoParserFound::~NoParserFound() {
  SharedDtor();
}

void NoParserFound::SharedDtor() {
  if (this != default_instance_) {
  }
}

void NoParserFound::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NoParserFound::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NoParserFound_descriptor_;
}

const NoParserFound& NoParserFound::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_NoParserFound_2eproto();
  return *default_instance_;
}

NoParserFound* NoParserFound::default_instance_ = NULL;

NoParserFound* NoParserFound::New() const {
  return new NoParserFound;
}

void NoParserFound::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    requestedparserid_ = 0u;
    receivedmessageid_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NoParserFound::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 requestedParserID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &requestedparserid_)));
          set_has_requestedparserid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_receivedMessageID;
        break;
      }

      // required uint32 receivedMessageID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_receivedMessageID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &receivedmessageid_)));
          set_has_receivedmessageid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NoParserFound::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 requestedParserID = 1;
  if (has_requestedparserid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->requestedparserid(), output);
  }

  // required uint32 receivedMessageID = 2;
  if (has_receivedmessageid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->receivedmessageid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NoParserFound::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 requestedParserID = 1;
  if (has_requestedparserid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->requestedparserid(), target);
  }

  // required uint32 receivedMessageID = 2;
  if (has_receivedmessageid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->receivedmessageid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NoParserFound::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 requestedParserID = 1;
    if (has_requestedparserid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->requestedparserid());
    }

    // required uint32 receivedMessageID = 2;
    if (has_receivedmessageid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->receivedmessageid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NoParserFound::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NoParserFound* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NoParserFound*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NoParserFound::MergeFrom(const NoParserFound& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_requestedparserid()) {
      set_requestedparserid(from.requestedparserid());
    }
    if (from.has_receivedmessageid()) {
      set_receivedmessageid(from.receivedmessageid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NoParserFound::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NoParserFound::CopyFrom(const NoParserFound& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NoParserFound::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void NoParserFound::Swap(NoParserFound* other) {
  if (other != this) {
    std::swap(requestedparserid_, other->requestedparserid_);
    std::swap(receivedmessageid_, other->receivedmessageid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NoParserFound::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NoParserFound_descriptor_;
  metadata.reflection = NoParserFound_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
