// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PiHeader.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PiHeader.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PiHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PiHeader_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PiHeader_2eproto() {
  protobuf_AddDesc_PiHeader_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PiHeader.proto");
  GOOGLE_CHECK(file != NULL);
  PiHeader_descriptor_ = file->message_type(0);
  static const int PiHeader_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PiHeader, messagelength_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PiHeader, parserid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PiHeader, messageid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PiHeader, flags_),
  };
  PiHeader_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PiHeader_descriptor_,
      PiHeader::default_instance_,
      PiHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PiHeader, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PiHeader, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PiHeader));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PiHeader_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PiHeader_descriptor_, &PiHeader::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PiHeader_2eproto() {
  delete PiHeader::default_instance_;
  delete PiHeader_reflection_;
}

void protobuf_AddDesc_PiHeader_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016PiHeader.proto\"U\n\010PiHeader\022\025\n\rmessageL"
    "ength\030\001 \002(\r\022\020\n\010parserID\030\002 \002(\r\022\021\n\tmessage"
    "ID\030\003 \001(\r\022\r\n\005flags\030\004 \001(\r", 103);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PiHeader.proto", &protobuf_RegisterTypes);
  PiHeader::default_instance_ = new PiHeader();
  PiHeader::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PiHeader_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PiHeader_2eproto {
  StaticDescriptorInitializer_PiHeader_2eproto() {
    protobuf_AddDesc_PiHeader_2eproto();
  }
} static_descriptor_initializer_PiHeader_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PiHeader::kMessageLengthFieldNumber;
const int PiHeader::kParserIDFieldNumber;
const int PiHeader::kMessageIDFieldNumber;
const int PiHeader::kFlagsFieldNumber;
#endif  // !_MSC_VER

PiHeader::PiHeader()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PiHeader::InitAsDefaultInstance() {
}

PiHeader::PiHeader(const PiHeader& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PiHeader::SharedCtor() {
  _cached_size_ = 0;
  messagelength_ = 0u;
  parserid_ = 0u;
  messageid_ = 0u;
  flags_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PiHeader::~PiHeader() {
  SharedDtor();
}

void PiHeader::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PiHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PiHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PiHeader_descriptor_;
}

const PiHeader& PiHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PiHeader_2eproto();
  return *default_instance_;
}

PiHeader* PiHeader::default_instance_ = NULL;

PiHeader* PiHeader::New() const {
  return new PiHeader;
}

void PiHeader::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    messagelength_ = 0u;
    parserid_ = 0u;
    messageid_ = 0u;
    flags_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PiHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 messageLength = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &messagelength_)));
          set_has_messagelength();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_parserID;
        break;
      }

      // required uint32 parserID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_parserID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &parserid_)));
          set_has_parserid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_messageID;
        break;
      }

      // optional uint32 messageID = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_messageID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &messageid_)));
          set_has_messageid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_flags;
        break;
      }

      // optional uint32 flags = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_flags:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &flags_)));
          set_has_flags();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PiHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 messageLength = 1;
  if (has_messagelength()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->messagelength(), output);
  }

  // required uint32 parserID = 2;
  if (has_parserid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->parserid(), output);
  }

  // optional uint32 messageID = 3;
  if (has_messageid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->messageid(), output);
  }

  // optional uint32 flags = 4;
  if (has_flags()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->flags(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PiHeader::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 messageLength = 1;
  if (has_messagelength()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->messagelength(), target);
  }

  // required uint32 parserID = 2;
  if (has_parserid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->parserid(), target);
  }

  // optional uint32 messageID = 3;
  if (has_messageid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->messageid(), target);
  }

  // optional uint32 flags = 4;
  if (has_flags()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->flags(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PiHeader::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 messageLength = 1;
    if (has_messagelength()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->messagelength());
    }

    // required uint32 parserID = 2;
    if (has_parserid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->parserid());
    }

    // optional uint32 messageID = 3;
    if (has_messageid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->messageid());
    }

    // optional uint32 flags = 4;
    if (has_flags()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->flags());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PiHeader::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PiHeader* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PiHeader*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PiHeader::MergeFrom(const PiHeader& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_messagelength()) {
      set_messagelength(from.messagelength());
    }
    if (from.has_parserid()) {
      set_parserid(from.parserid());
    }
    if (from.has_messageid()) {
      set_messageid(from.messageid());
    }
    if (from.has_flags()) {
      set_flags(from.flags());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PiHeader::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PiHeader::CopyFrom(const PiHeader& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PiHeader::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void PiHeader::Swap(PiHeader* other) {
  if (other != this) {
    std::swap(messagelength_, other->messagelength_);
    std::swap(parserid_, other->parserid_);
    std::swap(messageid_, other->messageid_);
    std::swap(flags_, other->flags_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PiHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PiHeader_descriptor_;
  metadata.reflection = PiHeader_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
