// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupRegistration.proto

#ifndef PROTOBUF_GroupRegistration_2eproto__INCLUDED
#define PROTOBUF_GroupRegistration_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GroupRegistration_2eproto();
void protobuf_AssignDesc_GroupRegistration_2eproto();
void protobuf_ShutdownFile_GroupRegistration_2eproto();

class GroupRegistration;

// ===================================================================

class GroupRegistration : public ::google::protobuf::MessageLite {
 public:
  GroupRegistration();
  virtual ~GroupRegistration();

  GroupRegistration(const GroupRegistration& from);

  inline GroupRegistration& operator=(const GroupRegistration& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GroupRegistration& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GroupRegistration* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GroupRegistration* other);

  // implements Message ----------------------------------------------

  GroupRegistration* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GroupRegistration& from);
  void MergeFrom(const GroupRegistration& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string groupID = 1;
  inline bool has_groupid() const;
  inline void clear_groupid();
  static const int kGroupIDFieldNumber = 1;
  inline const ::std::string& groupid() const;
  inline void set_groupid(const ::std::string& value);
  inline void set_groupid(const char* value);
  inline void set_groupid(const char* value, size_t size);
  inline ::std::string* mutable_groupid();
  inline ::std::string* release_groupid();
  inline void set_allocated_groupid(::std::string* groupid);

  // required bool addToGroup = 2;
  inline bool has_addtogroup() const;
  inline void clear_addtogroup();
  static const int kAddToGroupFieldNumber = 2;
  inline bool addtogroup() const;
  inline void set_addtogroup(bool value);

  // optional uint32 flags = 3;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 3;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // optional string clientName = 4;
  inline bool has_clientname() const;
  inline void clear_clientname();
  static const int kClientNameFieldNumber = 4;
  inline const ::std::string& clientname() const;
  inline void set_clientname(const ::std::string& value);
  inline void set_clientname(const char* value);
  inline void set_clientname(const char* value, size_t size);
  inline ::std::string* mutable_clientname();
  inline ::std::string* release_clientname();
  inline void set_allocated_clientname(::std::string* clientname);

  // @@protoc_insertion_point(class_scope:GroupRegistration)
 private:
  inline void set_has_groupid();
  inline void clear_has_groupid();
  inline void set_has_addtogroup();
  inline void clear_has_addtogroup();
  inline void set_has_flags();
  inline void clear_has_flags();
  inline void set_has_clientname();
  inline void clear_has_clientname();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* groupid_;
  bool addtogroup_;
  ::google::protobuf::uint32 flags_;
  ::std::string* clientname_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GroupRegistration_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GroupRegistration_2eproto();
  #endif
  friend void protobuf_AssignDesc_GroupRegistration_2eproto();
  friend void protobuf_ShutdownFile_GroupRegistration_2eproto();

  void InitAsDefaultInstance();
  static GroupRegistration* default_instance_;
};
// ===================================================================


// ===================================================================

// GroupRegistration

// required string groupID = 1;
inline bool GroupRegistration::has_groupid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GroupRegistration::set_has_groupid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GroupRegistration::clear_has_groupid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GroupRegistration::clear_groupid() {
  if (groupid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    groupid_->clear();
  }
  clear_has_groupid();
}
inline const ::std::string& GroupRegistration::groupid() const {
  // @@protoc_insertion_point(field_get:GroupRegistration.groupID)
  return *groupid_;
}
inline void GroupRegistration::set_groupid(const ::std::string& value) {
  set_has_groupid();
  if (groupid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    groupid_ = new ::std::string;
  }
  groupid_->assign(value);
  // @@protoc_insertion_point(field_set:GroupRegistration.groupID)
}
inline void GroupRegistration::set_groupid(const char* value) {
  set_has_groupid();
  if (groupid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    groupid_ = new ::std::string;
  }
  groupid_->assign(value);
  // @@protoc_insertion_point(field_set_char:GroupRegistration.groupID)
}
inline void GroupRegistration::set_groupid(const char* value, size_t size) {
  set_has_groupid();
  if (groupid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    groupid_ = new ::std::string;
  }
  groupid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:GroupRegistration.groupID)
}
inline ::std::string* GroupRegistration::mutable_groupid() {
  set_has_groupid();
  if (groupid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    groupid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:GroupRegistration.groupID)
  return groupid_;
}
inline ::std::string* GroupRegistration::release_groupid() {
  clear_has_groupid();
  if (groupid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = groupid_;
    groupid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GroupRegistration::set_allocated_groupid(::std::string* groupid) {
  if (groupid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete groupid_;
  }
  if (groupid) {
    set_has_groupid();
    groupid_ = groupid;
  } else {
    clear_has_groupid();
    groupid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:GroupRegistration.groupID)
}

// required bool addToGroup = 2;
inline bool GroupRegistration::has_addtogroup() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GroupRegistration::set_has_addtogroup() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GroupRegistration::clear_has_addtogroup() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GroupRegistration::clear_addtogroup() {
  addtogroup_ = false;
  clear_has_addtogroup();
}
inline bool GroupRegistration::addtogroup() const {
  // @@protoc_insertion_point(field_get:GroupRegistration.addToGroup)
  return addtogroup_;
}
inline void GroupRegistration::set_addtogroup(bool value) {
  set_has_addtogroup();
  addtogroup_ = value;
  // @@protoc_insertion_point(field_set:GroupRegistration.addToGroup)
}

// optional uint32 flags = 3;
inline bool GroupRegistration::has_flags() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GroupRegistration::set_has_flags() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GroupRegistration::clear_has_flags() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GroupRegistration::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 GroupRegistration::flags() const {
  // @@protoc_insertion_point(field_get:GroupRegistration.flags)
  return flags_;
}
inline void GroupRegistration::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:GroupRegistration.flags)
}

// optional string clientName = 4;
inline bool GroupRegistration::has_clientname() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GroupRegistration::set_has_clientname() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GroupRegistration::clear_has_clientname() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GroupRegistration::clear_clientname() {
  if (clientname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientname_->clear();
  }
  clear_has_clientname();
}
inline const ::std::string& GroupRegistration::clientname() const {
  // @@protoc_insertion_point(field_get:GroupRegistration.clientName)
  return *clientname_;
}
inline void GroupRegistration::set_clientname(const ::std::string& value) {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientname_ = new ::std::string;
  }
  clientname_->assign(value);
  // @@protoc_insertion_point(field_set:GroupRegistration.clientName)
}
inline void GroupRegistration::set_clientname(const char* value) {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientname_ = new ::std::string;
  }
  clientname_->assign(value);
  // @@protoc_insertion_point(field_set_char:GroupRegistration.clientName)
}
inline void GroupRegistration::set_clientname(const char* value, size_t size) {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientname_ = new ::std::string;
  }
  clientname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:GroupRegistration.clientName)
}
inline ::std::string* GroupRegistration::mutable_clientname() {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:GroupRegistration.clientName)
  return clientname_;
}
inline ::std::string* GroupRegistration::release_clientname() {
  clear_has_clientname();
  if (clientname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = clientname_;
    clientname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GroupRegistration::set_allocated_clientname(::std::string* clientname) {
  if (clientname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete clientname_;
  }
  if (clientname) {
    set_has_clientname();
    clientname_ = clientname;
  } else {
    clear_has_clientname();
    clientname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:GroupRegistration.clientName)
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GroupRegistration_2eproto__INCLUDED
