// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParseError.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ParseError.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_ParseError_2eproto() {
  delete ParseError::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_ParseError_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_ParseError_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ParseError::default_instance_ = new ParseError();
  ParseError::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ParseError_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_ParseError_2eproto_once_);
void protobuf_AddDesc_ParseError_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_ParseError_2eproto_once_,
                 &protobuf_AddDesc_ParseError_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ParseError_2eproto {
  StaticDescriptorInitializer_ParseError_2eproto() {
    protobuf_AddDesc_ParseError_2eproto();
  }
} static_descriptor_initializer_ParseError_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int ParseError::kErrorNumberFieldNumber;
const int ParseError::kErrorMessageFieldNumber;
#endif  // !_MSC_VER

ParseError::ParseError()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ParseError)
}

void ParseError::InitAsDefaultInstance() {
}

ParseError::ParseError(const ParseError& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ParseError)
}

void ParseError::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  errornumber_ = 0u;
  errormessage_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParseError::~ParseError() {
  // @@protoc_insertion_point(destructor:ParseError)
  SharedDtor();
}

void ParseError::SharedDtor() {
  if (errormessage_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete errormessage_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ParseError::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ParseError& ParseError::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_ParseError_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_ParseError_2eproto();
#endif
  return *default_instance_;
}

ParseError* ParseError::default_instance_ = NULL;

ParseError* ParseError::New() const {
  return new ParseError;
}

void ParseError::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    errornumber_ = 0u;
    if (has_errormessage()) {
      if (errormessage_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        errormessage_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool ParseError::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:ParseError)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 errorNumber = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &errornumber_)));
          set_has_errornumber();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_errorMessage;
        break;
      }

      // optional string errorMessage = 2;
      case 2: {
        if (tag == 18) {
         parse_errorMessage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_errormessage()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ParseError)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ParseError)
  return false;
#undef DO_
}

void ParseError::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ParseError)
  // optional uint32 errorNumber = 1;
  if (has_errornumber()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->errornumber(), output);
  }

  // optional string errorMessage = 2;
  if (has_errormessage()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->errormessage(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:ParseError)
}

int ParseError::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 errorNumber = 1;
    if (has_errornumber()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->errornumber());
    }

    // optional string errorMessage = 2;
    if (has_errormessage()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->errormessage());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParseError::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ParseError*>(&from));
}

void ParseError::MergeFrom(const ParseError& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_errornumber()) {
      set_errornumber(from.errornumber());
    }
    if (from.has_errormessage()) {
      set_errormessage(from.errormessage());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void ParseError::CopyFrom(const ParseError& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParseError::IsInitialized() const {

  return true;
}

void ParseError::Swap(ParseError* other) {
  if (other != this) {
    std::swap(errornumber_, other->errornumber_);
    std::swap(errormessage_, other->errormessage_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ParseError::GetTypeName() const {
  return "ParseError";
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
