// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParseError.proto

#ifndef PROTOBUF_ParseError_2eproto__INCLUDED
#define PROTOBUF_ParseError_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ParseError_2eproto();
void protobuf_AssignDesc_ParseError_2eproto();
void protobuf_ShutdownFile_ParseError_2eproto();

class ParseError;

// ===================================================================

class ParseError : public ::google::protobuf::Message {
 public:
  ParseError();
  virtual ~ParseError();

  ParseError(const ParseError& from);

  inline ParseError& operator=(const ParseError& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParseError& default_instance();

  void Swap(ParseError* other);

  // implements Message ----------------------------------------------

  ParseError* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParseError& from);
  void MergeFrom(const ParseError& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 errorNumber = 1;
  inline bool has_errornumber() const;
  inline void clear_errornumber();
  static const int kErrorNumberFieldNumber = 1;
  inline ::google::protobuf::uint32 errornumber() const;
  inline void set_errornumber(::google::protobuf::uint32 value);

  // optional string errorMessage = 2;
  inline bool has_errormessage() const;
  inline void clear_errormessage();
  static const int kErrorMessageFieldNumber = 2;
  inline const ::std::string& errormessage() const;
  inline void set_errormessage(const ::std::string& value);
  inline void set_errormessage(const char* value);
  inline void set_errormessage(const char* value, size_t size);
  inline ::std::string* mutable_errormessage();
  inline ::std::string* release_errormessage();
  inline void set_allocated_errormessage(::std::string* errormessage);

  // @@protoc_insertion_point(class_scope:ParseError)
 private:
  inline void set_has_errornumber();
  inline void clear_has_errornumber();
  inline void set_has_errormessage();
  inline void clear_has_errormessage();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* errormessage_;
  ::google::protobuf::uint32 errornumber_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_ParseError_2eproto();
  friend void protobuf_AssignDesc_ParseError_2eproto();
  friend void protobuf_ShutdownFile_ParseError_2eproto();

  void InitAsDefaultInstance();
  static ParseError* default_instance_;
};
// ===================================================================


// ===================================================================

// ParseError

// optional uint32 errorNumber = 1;
inline bool ParseError::has_errornumber() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParseError::set_has_errornumber() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParseError::clear_has_errornumber() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParseError::clear_errornumber() {
  errornumber_ = 0u;
  clear_has_errornumber();
}
inline ::google::protobuf::uint32 ParseError::errornumber() const {
  return errornumber_;
}
inline void ParseError::set_errornumber(::google::protobuf::uint32 value) {
  set_has_errornumber();
  errornumber_ = value;
}

// optional string errorMessage = 2;
inline bool ParseError::has_errormessage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParseError::set_has_errormessage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParseError::clear_has_errormessage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParseError::clear_errormessage() {
  if (errormessage_ != &::google::protobuf::internal::kEmptyString) {
    errormessage_->clear();
  }
  clear_has_errormessage();
}
inline const ::std::string& ParseError::errormessage() const {
  return *errormessage_;
}
inline void ParseError::set_errormessage(const ::std::string& value) {
  set_has_errormessage();
  if (errormessage_ == &::google::protobuf::internal::kEmptyString) {
    errormessage_ = new ::std::string;
  }
  errormessage_->assign(value);
}
inline void ParseError::set_errormessage(const char* value) {
  set_has_errormessage();
  if (errormessage_ == &::google::protobuf::internal::kEmptyString) {
    errormessage_ = new ::std::string;
  }
  errormessage_->assign(value);
}
inline void ParseError::set_errormessage(const char* value, size_t size) {
  set_has_errormessage();
  if (errormessage_ == &::google::protobuf::internal::kEmptyString) {
    errormessage_ = new ::std::string;
  }
  errormessage_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ParseError::mutable_errormessage() {
  set_has_errormessage();
  if (errormessage_ == &::google::protobuf::internal::kEmptyString) {
    errormessage_ = new ::std::string;
  }
  return errormessage_;
}
inline ::std::string* ParseError::release_errormessage() {
  clear_has_errormessage();
  if (errormessage_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = errormessage_;
    errormessage_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ParseError::set_allocated_errormessage(::std::string* errormessage) {
  if (errormessage_ != &::google::protobuf::internal::kEmptyString) {
    delete errormessage_;
  }
  if (errormessage) {
    set_has_errormessage();
    errormessage_ = errormessage;
  } else {
    clear_has_errormessage();
    errormessage_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ParseError_2eproto__INCLUDED
