// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ping.proto

#ifndef PROTOBUF_Ping_2eproto__INCLUDED
#define PROTOBUF_Ping_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Ping_2eproto();
void protobuf_AssignDesc_Ping_2eproto();
void protobuf_ShutdownFile_Ping_2eproto();

class Ping;

// ===================================================================

class Ping : public ::google::protobuf::Message {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ping& default_instance();

  void Swap(Ping* other);

  // implements Message ----------------------------------------------

  Ping* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 sentTime = 1;
  inline bool has_senttime() const;
  inline void clear_senttime();
  static const int kSentTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 senttime() const;
  inline void set_senttime(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Ping)
 private:
  inline void set_has_senttime();
  inline void clear_has_senttime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 senttime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Ping_2eproto();
  friend void protobuf_AssignDesc_Ping_2eproto();
  friend void protobuf_ShutdownFile_Ping_2eproto();

  void InitAsDefaultInstance();
  static Ping* default_instance_;
};
// ===================================================================


// ===================================================================

// Ping

// optional uint32 sentTime = 1;
inline bool Ping::has_senttime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ping::set_has_senttime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ping::clear_has_senttime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ping::clear_senttime() {
  senttime_ = 0u;
  clear_has_senttime();
}
inline ::google::protobuf::uint32 Ping::senttime() const {
  return senttime_;
}
inline void Ping::set_senttime(::google::protobuf::uint32 value) {
  set_has_senttime();
  senttime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Ping_2eproto__INCLUDED
